name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-Wall -Wconversion -Wextra -pedantic -Werror"

    - name: make
      run: cmake --build build

    - name: Card Unit Tests
      continue-on-error: true
      run: ctest --test-dir build -R CardTest --output-on-failure

    - name: Deck Unit Tests
      continue-on-error: true
      run: ctest --test-dir build -R DeckTest --output-on-failure

    - name: Hand Unit Tests
      continue-on-error: true
      run: ctest --test-dir build -R HandTest --output-on-failure

    - name: Card Manager Unit Tests
      continue-on-error: true
      run: ctest --test-dir build -R CardManagerTest --output-on-failure
